/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : SANE
 #	author : miyako
 #	2017/09/12
 #
 # --------------------------------------------------------------------------------*/

#include "libjson.h"
#include "libjson_methods.h"
#include "libusb.h"
#include "sane.h"
#include "sanei.h"
#include "saneopts.h"
#include "png.h"
#include "jpeglib.h"

#define BUFFER_SIZE 8192
#define READ_TIMEOUT 30
#define DEFAULT_RESOLUTION 300
#define INCHES_PER_METER (100.0/2.54)

// --- SANE
void SANE_SCANNERS_LIST(sLONG_PTR *pResult, PackagePtr pParams);
void SANE_Scan(sLONG_PTR *pResult, PackagePtr pParams);
void SANE_SCAN_OPTION_VALUES(sLONG_PTR *pResult, PackagePtr pParams);
void SANE_SET_SCAN_OPTION(sLONG_PTR *pResult, PackagePtr pParams);
void SANE_Get_scan_option(sLONG_PTR *pResult, PackagePtr pParams);

namespace SANE
{
	typedef enum
	{
		image_type_jpg = 0,
		image_type_png = 2
	}image_type_t;
}
